WIP Issue#91 Cooperation CRUD
ita-social-projects/Home pull request #103
Opened 2021-01-14 17:13 UTC by alexorlenko

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @Dandria1802 
- [ ] @OlTym 
- [ ] @Abhai2016 
- [ ] @Romanov-Niko 
- [ ] @PoLytvy 

### Second Level Review

- [ ] @kh0ma 

## Summary of issue

Add Cooperation CRUD into our project.
Add new Entities to home-data.

## Summary of change

ToDo

## Testing approach

-

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-14 18:37 UTC, Abhai2016 requested changes

2021-01-14 18:37 UTC, Abhai2016 commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/CooperationApiServiceImpl.java
> +
При создании ОСББ выдает 400 код с ошибкой "Bad Request" -.-

2021-01-14 19:37 UTC, alexorlenko commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/CooperationApiServiceImpl.java
> +
yes. that's why I do WIP. maybe someone helps me with this problem.

2021-01-18 08:37 UTC, OlTym reviewed
Need to check columns constraint in all entities. The are not unique ,nullable ,length constraint in this  entities.
Why House entity has only one column?  If it neccesary to set column default value.

2021-01-18 09:25 UTC, Dandria1802 commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/CooperationApiServiceImpl.java
> +
JUST fix patterns in yaml file..

2021-01-18 20:13 UTC, Romanov-Niko approved these changes

2021-01-20 11:18 UTC, kh0ma requested changes

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +      parameters:
Please consider using some filter parameters for this query. I'm sure that at least querying by name would be useful.

2021-01-20 11:18 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/CooperationApiServiceImpl.java
> +public class CooperationApiServiceImpl implements CooperationApiService {
What is about permissions?

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/Address.java
> +public class Address extends BaseEntity {
According to the design spec Address contains a bit more fields. How are you going to store it if you didn't specify it in Entity?

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/Cooperation.java
> +    private List<Email> emails;
Aren't we decided to follow STI and keep this data in one table (e.g. Contact)?

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/Cooperation.java
> +    private List<Phone> phones;
Aren't we decided to follow STI and keep this data in one table (e.g. Contact)?

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/Cooperation.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
To avoid the cycle load of relations please get rid of EAGER.

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/Email.java
> +    private Cooperation cooperation;
Do we really use this field now?

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/House.java
> +    private Cooperation cooperation;
Do we really use this field now?

2021-01-20 11:18 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/House.java
> +    private int area;
1. Do not use primitives
2. How you are going to store decimals?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +        "409":
What is it about and why do we need it here?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          $ref: '#/components/responses/Conflict'
Why do we need it?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +        "401":
If we following the approach to documenting most of the possible errors, can forbidden appear here?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +        "401":
If we following the approach to documenting most of the possible errors, can forbidden appear here?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +      required:
Are really everything required?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          maxLength: 50
Did you propagate this constraint to DB?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          maxLength: 12
Did you propagate this constraint to DB?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          maxLength: 50
Did you propagate this constraint to DB?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +        phoneCooperation:
I think phone and email could be combined into a contact array.

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +        houses:
We should omit cascade updating. How do you see it at all?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          type: integer
integer? Really?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          minLength: 10
What is about a pattern for validation?

2021-01-20 11:18 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +          minLength: 3
3? Really? a@a?

2021-01-20 11:18 UTC, kh0ma commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/CooperationDto.java
> +    private Address addressCooperation;
What is the naming of the field? Can it be simply `address`?

2021-01-20 14:02 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/Cooperation.java
> +    @OneToOne(cascade = CascadeType.ALL)
Please describe why we need it. (Cascade)

2021-02-26 12:59 UTC, closed without merging