Issue#104: Updated scripts according to new DB schema and added sequence
ita-social-projects/Home pull request #105
Opened 2021-01-15 08:27 UTC by PoLytvy

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-16 10:45 UTC, OlTym commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="NUMBER" type="VARCHAR(100)">
The column  dimention is too big 100

2021-01-16 10:46 UTC, OlTym commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="TITLE_DEED" type="VARCHAR(20)">
The column dimention is too small - 20

2021-01-16 10:49 UTC, OlTym commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> -            <column name="LOCKED" type="BOOLEAN">
This column is not in the shema

2021-01-16 10:50 UTC, OlTym commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> -            <column name="PASSWORD" type="VARCHAR">
This column is not in the shema

2021-01-17 17:07 UTC, Abhai2016 requested changes

2021-01-17 17:07 UTC, Abhai2016 commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="HOUSE_NUMBER" type="VARCHAR(255)">
I don't think that the number of house will be that big. We can choose 10 or even less for this instead of 255.

2021-01-17 17:07 UTC, Abhai2016 commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="NUMBER" type="VARCHAR(100)">
Yeah, we can set 10 or even less for the number of flat.

2021-01-17 17:07 UTC, Abhai2016 commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="TITLE_DEED" type="VARCHAR(20)">
Agree with the statement above.

2021-01-17 17:07 UTC, Abhai2016 commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> -            <column name="LOCKED" type="BOOLEAN">
That's why it was deleted.

2021-01-17 17:07 UTC, Abhai2016 commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> -            <column name="PASSWORD" type="VARCHAR">
Same as above.

2021-01-17 17:07 UTC, Abhai2016 commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="TITLE" type="VARCHAR(255)">
I guess we can set here 150 as in adverts.

2021-01-18 08:48 UTC, OlTym reviewed
need to check all column namber and name, all column constraints such as unique ,nullable ,length. If it neccesary to set default value.

2021-01-18 11:57 UTC, PoLytvy commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="NUMBER" type="VARCHAR(100)">
Fixed

2021-01-18 11:57 UTC, PoLytvy commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="TITLE_DEED" type="VARCHAR(20)">
Fixed

2021-01-18 11:57 UTC, PoLytvy commented on home-data-migration/src/main/resources/db/changelog/0.0.1/Issue33.xml
> +            <column name="HOUSE_NUMBER" type="VARCHAR(255)">
Fixed

2021-01-18 14:04 UTC, Romanov-Niko approved these changes

2021-01-18 14:25 UTC, Abhai2016 approved these changes

2021-01-18 14:40 UTC, Dandria1802 approved these changes

2021-01-18 14:41 UTC, alexorlenko approved these changes

2021-01-18 14:42 UTC, merged