Issue#71 improvement proposal
ita-social-projects/Home pull request #143
Opened 2021-02-03 18:35 UTC by OlTym

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-02-05 07:47 UTC, kh0ma commented
@OlTym Please name the pull request properly. Ideally, it should be named after the issue name.

2021-02-05 08:23 UTC, kh0ma requested changes

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/pom.xml
> +                                <home.application.admin.username>${home.application.admin.username}
What and why do we change here?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/NewsApiIT.java
> +     }
Why did we change it?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/NewsApiIT.java
> +        newsApi.deleteNews(readNews.getId());
What's the purpose?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/NewsApiIT.java
> +        newsApi.deleteNews(savedNews.getId());
What's the purpose?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/NewsApiIT.java
> -    void getAllNewsTest() throws ApiException {
Why did we remove it? It should still exist.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/NewsApiIT.java
> +        newsApi.deleteNews(savedNews.getId());
What's the purpose?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +public class RSQLNewsIT {
Please avoid underlying technology in this naming. We are testing the query endpoint but not the technology we were used. Also, let's keep the test in one place for the API. It could be a nested test or just wrap it via package but all NewsApi tests should be connected.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        createManyNews();
Please avoid creating smth in before each test. Create particular test data for the concrete test.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +    private void initParameters() {
What is the purpose of it? Can we get rid of it?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        title = newsList.get((int) (Math.random() * newsList.size())).getTitle();
Are you sure about using random in tests? It could bring absolutely unexpected behavior between runs. The only case when it is suitable is to avoid duplicates for unique fields.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        List<ReadNews> listNews = newsApi
Please refactor creating the query via builder pattern. Place it somewhere in utils.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        listNews.forEach(ReadNews -> assertEquals(ReadNews.getTitle(), title));
Please use the proper case for naming variables.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        assertFalse(listNews.isEmpty());
Can we also verify the result?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        filter = new StringBuilder()
Can we make RSQL specific builder based on tokens? Place it in utils.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +        assertEquals(listNews.size(), 4);
How do we know the exact size? What if more than 4 exist in db? Sound like this test is dirty.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +                .withMessage(new StringBuilder()
Why cannot we use ApiException model for building it?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +            newsApi.deleteNews(ru.getId());
I personally think that the data we created during test running could be useful after test completed. We can access it through postman and verify additionally when we troubleshoot some scenarios.

Please explain the purpose of deleting this data.

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +    private Optional<List<CreateNews>> createNewsList() {
What is the purpose of using `Optional` here?

2021-02-05 08:23 UTC, kh0ma commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLUserIT.java
> +public class RSQLUserIT {
I expect comments to be the same a for the previous test. Please fix them also for this one.

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/CommonApiService.java
> +public abstract class CommonApiService<R extends BaseDto> {
CommonApi

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/NewsApiImpl.java
> +    private EntitySpecificationService entitySpecificationService;
I think we can inject this bean into CommonApi and access it through a protected getter. The same situation for the mapper.

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/NewsApiImpl.java
> +        Map<QueryParamEnum, String> filterMap = new HashMap<>();
Can we build this map using some builder?

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/NewsApiImpl.java
> +     * @param id         is id of the news that has to be updated
Why did we change it?

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/NewsApiImpl.java
> +
Why did we add this line?

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/UserApiImpl.java
> +        super.setMapper(mapper);
?

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/config/rsql/UserRSQLEndpointConfig.java
> +//@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
?

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/config/rsql/UserRSQLEndpointConfig.java
> +
Extra line?

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/jax/BadRequestExceptionMapper.java
> +public class BadRequestExceptionMapper extends BaseExceptionMapper<RSQLParserException> {
The name of a mapper should be after the exception it maps
RSQLParserExceptionMapper

2021-02-05 08:23 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/jax/BadRequestExceptionMapper.java
> +        return "Illegal argument for request.";
Please handle the exception and provide a more informative message.

2021-02-05 08:23 UTC, kh0ma commented on home-data/src/main/resources/application.properties
> +spring.datasource.password=${DATASOURCE_PASSWORD:postgres}
?

2021-02-05 08:23 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/openapi.yaml
> +      operationId: getAllUsers
Why did we change it?

2021-02-05 08:23 UTC, kh0ma commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/mapper/ServiceMapper.java
> +
?

2021-02-05 08:23 UTC, kh0ma commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/query/impl/UserQueryConfig.java
> +//@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
?

2021-02-06 12:47 UTC, OlTym commented on home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/RSQLNewsIT.java
> +public class RSQLNewsIT {
done

2021-02-11 12:25 UTC, closed without merging