Issue#153 map and handle constrain violations in presentation models
ita-social-projects/Home pull request #174
Opened 2021-02-19 19:17 UTC by annaprok

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-02-22 21:37 UTC, kh0ma requested changes

2021-02-22 21:37 UTC, kh0ma commented on home-clients/pom.xml
> +        <dependency>
why do we need this change?

2021-02-23 07:11 UTC, annaprok commented on home-clients/pom.xml
> +        <dependency>
Change deleted

2021-02-23 10:32 UTC, Abhai2016 approved these changes

2021-02-23 10:32 UTC, Abhai2016 commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/GeneralExceptionMapper.java
> +
Why do we need this extra line?

2021-02-24 07:57 UTC, kh0ma requested changes

2021-02-24 07:57 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/ConstraintViolationMapper.java
> +        for (Map.Entry<String, String> entry : parameters.entrySet()) {
It is a piece of hardcode. The solution must be extendable.

2021-02-27 09:05 UTC, ElgorTheWanderer commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/ConstraintViolationMapper.java
> +}
Lines 14, 47, 48 are redundant.

2021-02-27 09:06 UTC, ElgorTheWanderer approved these changes

2021-02-27 09:13 UTC, ElgorTheWanderer requested changes

2021-02-27 09:13 UTC, ElgorTheWanderer commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/ConstraintViolationMapper.java
> +import java.util.Map;
You need to change imports order according to code style. CI fails because you have import order violations.

2021-03-03 14:58 UTC, Abhai2016 commented on home-application/src/main/resources/ValidationMessages.properties
> +javax.validation.constraints.Pattern.message=must meet the rule
Add a new line in the end of the line.

2021-03-03 14:58 UTC, dd994 approved these changes

2021-03-03 15:02 UTC, denis-litvinov approved these changes

2021-03-05 13:05 UTC, kh0ma requested changes

2021-03-05 13:05 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/ConstraintViolationMapper.java
> +public class ConstraintViolationMapper extends BaseExceptionMapper<ConstraintViolationException> {
ConstraintViolationExceptionMapper

2021-03-05 13:05 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/exception/mapper/ConstraintViolationMapper.java
> +        return result.toString().trim();
We can avoid such ugly `trim` here using streams:
```java
    private String handleConstraintViolationExceptionMessage(ConstraintViolationException exception) {
        return exception.getConstraintViolations().stream()
                .map(violation -> String.format("Field `%s` is invalid: %s.", 
                        getParameterFromPropertyPath(violation.getPropertyPath()), 
                        violation.getMessage())
                )
                .collect(Collectors.joining(" "));
    }
   
```

2021-03-07 13:33 UTC, ElgorTheWanderer approved these changes

2021-03-09 14:55 UTC, kh0ma approved these changes

2021-03-09 15:09 UTC, merged