Issue#154: corrected plugin in pom.xml in open-api module
ita-social-projects/Home pull request #176
Opened 2021-02-24 11:09 UTC by denis-litvinov

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-02-25 15:46 UTC, alexorlenko approved these changes

2021-02-25 16:57 UTC, dd994 approved these changes

2021-02-26 13:17 UTC, kh0ma requested changes

2021-02-26 13:17 UTC, kh0ma commented on home-open-api/pom.xml
> +                    <inputFile>${project.basedir}/src/main/resources/yaml/openapi.yaml</inputFile>
`${project.build.resources[0].directory}/yaml/openapi.yaml`

2021-02-26 17:09 UTC, annaprok approved these changes

2021-02-26 18:07 UTC, ElgorTheWanderer approved these changes

2021-02-26 21:55 UTC, kh0ma approved these changes

2021-02-28 13:03 UTC, Abhai2016 approved these changes

2021-03-01 07:13 UTC, merged