Issue#163 create database sequences
ita-social-projects/Home pull request #185
Opened 2021-03-09 20:55 UTC by dd994

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-09 21:02 UTC, kh0ma requested changes
I left comments here https://github.com/ita-social-projects/Home/pull/184 Please take them into account

2021-03-14 20:11 UTC, kh0ma approved these changes

2021-03-14 20:11 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/BaseEntity.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "sequence")
Didn't you miss a space after the comma?

2021-03-15 14:22 UTC, denis-litvinov approved these changes

2021-03-15 15:09 UTC, ElgorTheWanderer approved these changes

2021-03-15 17:57 UTC, annaprok approved these changes

2021-03-15 19:06 UTC, merged