WIP Issue#168 configure sonar code coverage
ita-social-projects/Home pull request #187
Opened 2021-03-23 21:26 UTC by annaprok

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-26 21:31 UTC, kh0ma requested changes

2021-03-26 21:31 UTC, kh0ma commented on home-api-tests/pom.xml
> +                                            <MD5>d4db29ddfdb2753aaaa3e4dd67a0521e</MD5>
Why do we need this var?

2021-03-26 22:11 UTC, Abhai2016 approved these changes

2021-03-26 23:23 UTC, VadymSokorenko approved these changes

2021-03-26 23:23 UTC, VadymSokorenko commented on home-api-tests/pom.xml
> +                                <phase>initialize</phase>
Why do we set phase to `initialize`? Can we bind it to `validate`?

2021-03-29 11:05 UTC, kh0ma approved these changes

2021-03-29 11:15 UTC, denis-litvinov approved these changes

2021-03-29 11:16 UTC, merged