Issue#326 add support of swagger UI and re doc openapi viewers
ita-social-projects/Home pull request #328
Opened 2021-10-08 14:04 UTC by OliMpiX

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-10-08 22:30 UTC, kh0ma requested changes

2021-10-08 22:30 UTC, kh0ma commented on home-application/pom.xml
> +                                    <artifactId>home-open-api</artifactId>
I don't think we need to extract open-api thrice. Just extract it as additional execution and name it `resource-dependencies-openapi-cpec`

2021-10-08 22:30 UTC, kh0ma commented on home-application/pom.xml
> +                            <includes>*/openapi.yaml,*/openapi.json,**/3.52.3/*</includes>
since you will have open-api as an additional execution you can remove '*/openapi.yaml,*/openapi.json,' from this filter

2021-10-08 22:30 UTC, kh0ma commented on home-application/src/main/resources/static/api/0/apidocs/index.html
> +</html>
Please add newline at the end of the file.

https://unix.stackexchange.com/a/18744

2021-10-08 22:30 UTC, kh0ma commented on home-application/src/main/resources/static/api/0/apidocs/redoc/index.html
> +</html>
Add newline

2021-10-11 13:07 UTC, bbogdasha approved these changes

2021-10-11 13:11 UTC, SerhiiPakulia approved these changes

2021-10-11 14:45 UTC, OliMpiX commented on home-application/pom.xml
> +                                    <artifactId>home-open-api</artifactId>
Understood. Done.

2021-10-11 14:46 UTC, OliMpiX commented on home-application/pom.xml
> +                            <includes>*/openapi.yaml,*/openapi.json,**/3.52.3/*</includes>
Ok, I removed them from the filter.

2021-10-11 14:47 UTC, OliMpiX commented on home-application/src/main/resources/static/api/0/apidocs/index.html
> +</html>
Thanks for the link. Added extra lines i 2 index.html files.

2021-10-11 14:48 UTC, OliMpiX commented on home-application/src/main/resources/static/api/0/apidocs/redoc/index.html
> +</html>
Done.

2021-10-11 17:39 UTC, kh0ma approved these changes

2021-10-11 19:09 UTC, KirillAndriushchenko approved these changes

2021-10-11 19:42 UTC, merged