Update readOwnership by changing Readuser to ReadOwner model.
ita-social-projects/Home pull request #346
Opened 2021-11-11 16:26 UTC by varhanovdm

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/333)

## Code reviewers

- [ ] @bbogdasha 
- [ ] @kh0ma 
- [ ] @Pavlo-Ponomarenko 
- [ ] @DzigMS 

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-11-12 09:02 UTC, kh0ma requested changes

2021-11-12 09:02 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/mapper/config/impl/ReadOwnerMappingConfig.java
> +}
Please add newline to the end of the file https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2021-11-12 09:02 UTC, kh0ma commented on home-open-api/src/main/resources/yaml/models/owner.yaml
> +        $ref: 'contact.yaml#/ReadContact'
Newline

2021-11-12 13:56 UTC, varhanovdm commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/mapper/config/impl/ReadOwnerMappingConfig.java
> +}
Ok

2021-11-12 15:10 UTC, bbogdasha approved these changes

2021-11-12 15:13 UTC, Pavlo-Ponomarenko approved these changes

2021-11-12 15:20 UTC, varhanovdm commented on home-open-api/src/main/resources/yaml/models/owner.yaml
> +        $ref: 'contact.yaml#/ReadContact'
Fixed

2021-11-15 08:40 UTC, kh0ma approved these changes

2021-11-15 12:07 UTC, merged