Bug/issue#423 poll can be created in past
ita-social-projects/Home pull request #424
Opened 2022-05-05 14:46 UTC by lEquinoXl

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

-Create verification of creation date in polls
-Create api test for new case

## Summary of change

-Added verification for creation date in polls
-Added test and api test for new case
-Changed test "createPollWithDeletedHouseTest" to pass new verification

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-05-06 11:40 UTC, vladyslavyarets commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/service/poll/PollServiceImpl.java
> +        validateCreationDate(poll.getCreationDate(), "Poll has already started");
It's seems like logic violation here. You check creation date of poll which already stored in DB. This validation already passed during poll creation in line 73. Consider validation of pollDto which provided in parameters and matching creationDate of pollDto and poll which loads from DB in line 90

2022-05-06 11:42 UTC, vladyslavyarets requested changes

2022-05-06 11:42 UTC, vladyslavyarets commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/service/poll/PollServiceImpl.java
> +        validateCreationDate(poll.getCreationDate(), "Poll has already started");
It's seems like logic violation here. You check creation date of poll which already stored in DB. This validation already passed during poll creation in line 73. Consider validation of pollDto which provided in parameters and matching creationDate of pollDto and poll which loads from DB in line 90

2022-05-06 11:42 UTC, vladyslavyarets commented on home-service/src/test/java/com/softserveinc/ita/homeproject/homeservice/service/impl/PollServiceImplTest.java
> +        assertThrows(BadRequestHomeException.class, () -> pollService.create(1L, poll));
Specify your exception checking with massage validation. For this you can use assertThatExceptionOfType() form assertj library

2022-05-06 16:05 UTC, vladyslavyarets approved these changes

2022-05-13 12:11 UTC, MrScors approved these changes

2022-05-13 12:32 UTC, merged