Create class for error messages
ita-social-projects/Home pull request #465
Opened 2022-07-20 12:49 UTC by ystoikov

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/388)

## Summary of issue

Needed to create a class for error messages

## Summary of change

- Add a new ExceptionMessages class that aggregates all error messages from the project
- Replace  all messages in exception parameters
- Add static import to classes with replaced messages

## Testing approach

Not required

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-07-20 18:42 UTC, vladyslavyarets requested changes

2022-07-20 18:42 UTC, vladyslavyarets commented on home-oauth-server/src/main/java/com/softserveinc/ita/homeproject/homeoauthserver/service/OauthServiceImpl.java
> +
Please, remove this one unnecessary empty line

2022-07-20 18:42 UTC, vladyslavyarets commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/exception/ExceptionMessages.java
> +
Please, remove this one unnecessary empty line. You don't need it before closing bracket

2022-07-21 08:53 UTC, vladyslavyarets approved these changes

2022-07-21 08:54 UTC, vladyslavyarets commented
@MrScors @DzigMS we need your help to handle Sonar Cloud Quality Gate issues

2022-07-21 10:17 UTC, gendalf-fx approved these changes
Nice

2022-07-21 13:31 UTC, merged