Issue#52: Add health checks to application
ita-social-projects/Home pull request #73
Opened 2020-11-30 14:30 UTC by mykytam

dev
## ZenHub

* [Main ZenHub ticket](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/52)

## Code reviewers

- [ ] @alexorlenko
- [ ] @Arthurpanda
- [ ] @mykytam 
- [ ] @omelchenkotimur 
- [ ] @Prosperro-de 
- [ ] @reeztl 

### Second Level Review

- [ ] @DzigMS 
- [ ] @kh0ma 

## Summary of issue

Add a service that can health check API endpoint (e.g. HTTP /health) that returns the health of the service.

## Summary of change

In result of cheking the health of application, I can determine the status of the system under test.

Add Spring Actuator dependency
Add /health endpoint
Add custom db health check

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-02 15:51 UTC, alexorlenko approved these changes

2020-12-03 15:26 UTC, Arthurpanda approved these changes

2020-12-04 11:42 UTC, kh0ma requested changes

2020-12-04 11:42 UTC, kh0ma commented on home-application/src/main/resources/config/application.properties
> +management.server.port=${SERVER_PORT:8090}
`SERVER_PORT` -> `MANAGEMENT_SERVER_PORT`

2020-12-04 11:43 UTC, kh0ma commented
LGTM with suggested changes :+1:

2020-12-04 13:23 UTC, kh0ma approved these changes

2020-12-04 13:26 UTC, merged