Issue#51
ita-social-projects/Home pull request #76
Opened 2020-12-02 16:55 UTC by alexorlenko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @reeztl 
- [ ] @Arthurpanda 
- [ ] @mykytam 
- [ ] @omelchenkotimur 

### Second Level Review

- [ ] @kh0ma 
- [ ] @DzigMS 

## Summary of issue

Add mapstruct
Add BaseDto and BaseEntity

## Summary of change

Some change into openapi.yaml

## Testing approach

-

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-03 15:28 UTC, mykytam approved these changes

2020-12-04 13:59 UTC, kh0ma requested changes

2020-12-04 13:59 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/NewsApiServiceImpl.java
> +import com.softserveinc.ita.homeproject.homeservice.mapperViewToDto.CreateNewsDtoMapper;
`com.softserveinc.ita.homeproject.homeservice.mapper.*`

2020-12-04 13:59 UTC, kh0ma commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/NewsApiServiceImpl.java
> +        NewsDto readNewsDto = newsService.create(newsDto);
readNewsDto -> createdNewsDto

2020-12-04 13:59 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/BaseEntity.java
> +@MappedSuperclass
Eq and Hashcode

2020-12-04 13:59 UTC, kh0ma commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/BaseEntity.java
> +    protected Long id;
private

2020-12-04 13:59 UTC, kh0ma commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/BaseDto.java
> +public abstract class BaseDto {
id?

2020-12-04 13:59 UTC, kh0ma commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/NewsDto.java
> +    public NewsDto() {
Lombok?

2020-12-04 13:59 UTC, kh0ma commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/mapperViewToDto/DtoToViewMapper.java
> +public interface DtoToViewMapper<ServiceDto extends BaseDto, ViewDto> {
Can we introduce base View in design?

2020-12-04 15:59 UTC, alexorlenko reviewed
Yes we will change

2020-12-04 15:59 UTC, alexorlenko commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/NewsApiServiceImpl.java
> +import com.softserveinc.ita.homeproject.homeservice.mapperViewToDto.CreateNewsDtoMapper;
Done

2020-12-04 15:59 UTC, alexorlenko commented on home-application/src/main/java/com/softserveinc/ita/homeproject/application/apiservice/NewsApiServiceImpl.java
> +        NewsDto readNewsDto = newsService.create(newsDto);
Done

2020-12-04 15:59 UTC, alexorlenko commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/BaseEntity.java
> +    protected Long id;
Done

2020-12-04 15:59 UTC, alexorlenko commented on home-data/src/main/java/com/softserveinc/ita/homeproject/homedata/entity/BaseEntity.java
> +@MappedSuperclass
Done

2020-12-07 09:30 UTC, alexorlenko commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/NewsDto.java
> +    public NewsDto() {
Done

2020-12-21 12:17 UTC, alexorlenko commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/mapperViewToDto/DtoToViewMapper.java
> +public interface DtoToViewMapper<ServiceDto extends BaseDto, ViewDto> {
Done

2020-12-21 13:15 UTC, alexorlenko commented on home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/BaseDto.java
> +public abstract class BaseDto {
not now

2020-12-23 11:20 UTC, Romanov-Niko approved these changes

2020-12-23 11:33 UTC, Dandria1802 approved these changes

2020-12-23 12:24 UTC, PoLytvy approved these changes

2020-12-23 12:50 UTC, Abhai2016 approved these changes

2020-12-23 21:52 UTC, kh0ma commented on pom.xml
> +            <artifactId>mapstruct-processor</artifactId>
This dependency was added several times including distribution management. Please make it once. The same for `mapstruct`.

2020-12-23 21:53 UTC, kh0ma approved these changes
Approve with suggested changes

2020-12-24 07:40 UTC, merged